### ISSUE TITLE
Doesn't seem to work on .scss files

### ISSUE THREAD

**Issue by luisfontes** [adrianlee44/atom-aligner-css#1]
Hi,

First thanks for the package, great idea.

I can't get it to work on .scss files. For .css it is working as expected.

Let me know if you need more info.

**Comment by adrianlee44** [comment]
Hi @luisfontes, thanks for using the package. I have updated this package but unfortunate I had to move `scss/sass` support to its own package

You can find the support at [aligner-scss](https://github.com/adrianlee44/atom-aligner-scss)
